# Generated by Django 4.0.2 on 2022-02-16 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=100)),
                ('question_text', models.TextField(max_length=50000)),
                ('question_type', models.CharField(choices=[('Easy peasy lemon squeezy', 'Easy peasy lemon squeezy'), ('Not so easy and not so hard too...', 'Not so easy and not so hard too...'), ('Hard question good make sure you have good knoledge about programing', 'Hard question good make sure you have good knoledge about programing'), ('good your are mastreing the programing', 'good your are mastreing the programing')], max_length=100, null=True)),
                ('points', models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20')], max_length=3, null=True)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('ques', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.question')),
                ('test', models.TextField(max_length=10000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
